# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 520)
        MainWindow.setMinimumSize(QtCore.QSize(800, 520))
        MainWindow.setMaximumSize(QtCore.QSize(800, 520))
        MainWindow.setBaseSize(QtCore.QSize(800, 520))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(620, -10, 20, 471))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 300, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.wczytaj_mapy = QtWidgets.QPushButton(self.centralwidget)
        self.wczytaj_mapy.setGeometry(QtCore.QRect(700, 10, 91, 21))
        self.wczytaj_mapy.setObjectName("wczytaj_mapy")
        self.test1 = QtWidgets.QPushButton(self.centralwidget)
        self.test1.setGeometry(QtCore.QRect(640, 10, 42, 21))
        self.test1.setObjectName("test1")
        self.test2 = QtWidgets.QPushButton(self.centralwidget)
        self.test2.setGeometry(QtCore.QRect(640, 30, 42, 21))
        self.test2.setObjectName("test2")
        self.test3 = QtWidgets.QPushButton(self.centralwidget)
        self.test3.setGeometry(QtCore.QRect(640, 50, 42, 21))
        self.test3.setObjectName("test3")

        self.H_select = QtWidgets.QPushButton(self.centralwidget)
        self.H_select.setGeometry(QtCore.QRect(600, 10, 21, 21))
        self.H_select.setObjectName("H_select")
        self.T_select = QtWidgets.QPushButton(self.centralwidget)
        self.T_select.setGeometry(QtCore.QRect(600, 30, 21, 21))
        self.T_select.setObjectName("T_select")
        self.N_select = QtWidgets.QPushButton(self.centralwidget)
        self.N_select.setGeometry(QtCore.QRect(600, 50, 21, 21))
        self.N_select.setObjectName("N_select")

        self.wygeneruj_mapy = QtWidgets.QPushButton(self.centralwidget)
        self.wygeneruj_mapy.setGeometry(QtCore.QRect(700, 50, 91, 21))
        self.wygeneruj_mapy.setObjectName("wygeneruj_mapy")
        self.zapisz_mapy = QtWidgets.QPushButton(self.centralwidget)
        self.zapisz_mapy.setGeometry(QtCore.QRect(700, 30, 91, 21))
        self.zapisz_mapy.setObjectName("zapisz_mapy")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 100, 35, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(708, 100, 35, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 75, 91, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.size_map = QtWidgets.QSpinBox(self.centralwidget)
        self.size_map.setEnabled(True)
        self.size_map.setGeometry(QtCore.QRect(750, 75, 41, 22))
        self.size_map.setFrame(True)
        self.size_map.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.size_map.setReadOnly(False)
        self.size_map.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.size_map.setSpecialValueText("")
        self.size_map.setAccelerated(False)
        self.size_map.setKeyboardTracking(True)
        self.size_map.setMaximum(500)
        self.size_map.setMinimum(50)
        self.size_map.setProperty("value", 100)
        self.size_map.setObjectName("size_map")
        self.start_x = QtWidgets.QSpinBox(self.centralwidget)
        self.start_x.setGeometry(QtCore.QRect(670, 100, 41, 22))
        self.start_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.start_x.setMaximum(500)
        self.start_x.setProperty("value", 5)
        self.start_x.setObjectName("start_x")
        self.end_x = QtWidgets.QSpinBox(self.centralwidget)
        self.end_x.setGeometry(QtCore.QRect(750, 100, 41, 22))
        self.end_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.end_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.end_x.setMaximum(500)
        self.end_x.setProperty("value", 80)
        self.end_x.setObjectName("end_x")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 145, 91, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.max_energy = QtWidgets.QSpinBox(self.centralwidget)
        self.max_energy.setGeometry(QtCore.QRect(750, 145, 41, 22))
        self.max_energy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_energy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_energy.setMaximum(50000)
        self.max_energy.setObjectName("max_energy")
        self.max_energy.setProperty("value", 5000)
        self.war_zakonczenia_lab = QtWidgets.QLabel(self.centralwidget)
        self.war_zakonczenia_lab.setGeometry(QtCore.QRect(630, 405, 91, 16))
        self.war_zakonczenia_lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.war_zakonczenia_lab.setObjectName("war_zakonczenia_lab")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(630, 430, 91, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.iter = QtWidgets.QSpinBox(self.centralwidget)
        self.iter.setGeometry(QtCore.QRect(730, 430, 41, 22))
        self.iter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.iter.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.iter.setMaximum(10000)
        self.iter.setObjectName("iter")
        self.iter.setProperty("value", 50)
        self.war_zakonczenia = QtWidgets.QSpinBox(self.centralwidget)
        self.war_zakonczenia.setGeometry(QtCore.QRect(730, 405, 41, 22))
        self.war_zakonczenia.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.war_zakonczenia.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.war_zakonczenia.setMaximum(10000)
        self.war_zakonczenia.setObjectName("war_zakonczenia")
        self.war_zakonczenia.setProperty("value", 0)
        self.uruchom_algorytm = QtWidgets.QPushButton(self.centralwidget)
        self.uruchom_algorytm.setGeometry(QtCore.QRect(650, 455, 121, 21))
        self.uruchom_algorytm.setObjectName("uruchom_algorytm")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 170, 21, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(640, 190, 21, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.HCE = QtWidgets.QSpinBox(self.centralwidget)
        self.HCE.setGeometry(QtCore.QRect(670, 170, 41, 22))
        self.HCE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HCE.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.HCE.setMaximum(50)
        self.HCE.setProperty("value", 1)
        self.HCE.setObjectName("HCE")
        self.TCE = QtWidgets.QSpinBox(self.centralwidget)
        self.TCE.setGeometry(QtCore.QRect(670, 190, 41, 22))
        self.TCE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TCE.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.TCE.setMaximum(50)
        self.TCE.setProperty("value", 1)
        self.TCE.setObjectName("TCE")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(720, 190, 21, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(720, 170, 21, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.TCT = QtWidgets.QSpinBox(self.centralwidget)
        self.TCT.setGeometry(QtCore.QRect(750, 190, 41, 22))
        self.TCT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TCT.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.TCT.setMaximum(50)
        self.TCT.setProperty("value", 1)
        self.TCT.setObjectName("TCT")
        self.HCT = QtWidgets.QSpinBox(self.centralwidget)
        self.HCT.setGeometry(QtCore.QRect(750, 170, 41, 22))
        self.HCT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HCT.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.HCT.setMaximum(50)
        self.HCT.setProperty("value", 1)
        self.HCT.setObjectName("HCT")
        self.label_sun_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_sun_1.setGeometry(QtCore.QRect(640, 210, 21, 21))
        self.label_sun_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_sun_1.setObjectName("label_sun_1")
        self.label_sun_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sun_2.setGeometry(QtCore.QRect(720, 210, 21, 21))
        self.label_sun_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_sun_2.setObjectName("label_sun_2")
        self.sn1 = QtWidgets.QSpinBox(self.centralwidget)
        self.sn1.setGeometry(QtCore.QRect(670, 210, 41, 22))
        self.sn1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sn1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sn1.setMaximum(50)
        self.sn1.setProperty("value", 8)
        self.sn1.setObjectName("sn1")
        self.sn2 = QtWidgets.QSpinBox(self.centralwidget)
        self.sn2.setGeometry(QtCore.QRect(750, 210, 41, 22))
        self.sn2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sn2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sn2.setMaximum(50)
        self.sn2.setProperty("value", 4)
        self.sn2.setObjectName("sn2")
        self.label_aspiration = QtWidgets.QLabel(self.centralwidget)
        self.label_aspiration.setGeometry(QtCore.QRect(640, 250, 21, 21))
        self.label_aspiration.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_aspiration.setObjectName("label_aspiration")
        self.aspiration = QtWidgets.QSpinBox(self.centralwidget)
        self.aspiration.setGeometry(QtCore.QRect(670, 250, 41, 22))
        self.aspiration.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.aspiration.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.aspiration.setMaximum(500)
        self.aspiration.setObjectName("aspiration")
        self.aspiration.setProperty("value", 10)
        self.label_random = QtWidgets.QLabel(self.centralwidget)
        self.label_random.setGeometry(QtCore.QRect(720, 250, 21, 21))
        self.label_random.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_random.setObjectName("label_random")
        self.random_point = QtWidgets.QSpinBox(self.centralwidget)
        self.random_point.setGeometry(QtCore.QRect(750, 250, 41, 22))
        self.random_point.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.random_point.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.random_point.setMaximum(100)
        self.random_point.setMinimum(1)
        self.random_point.setObjectName("random_point")
        self.random_point.setProperty("value", 5)

        self.label_kt1 = QtWidgets.QLabel(self.centralwidget)
        self.label_kt1.setGeometry(QtCore.QRect(640, 275, 21, 21))
        self.label_kt1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_kt1.setObjectName("label_kt1")
        self.kt1 = QtWidgets.QSpinBox(self.centralwidget)
        self.kt1.setGeometry(QtCore.QRect(670, 275, 41, 22))
        self.kt1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.kt1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kt1.setMaximum(10000)
        self.kt1.setMinimum(5)
        self.kt1.setObjectName("kt1")
        self.kt1.setProperty("value", 30)
        self.label_kt2 = QtWidgets.QLabel(self.centralwidget)
        self.label_kt2.setGeometry(QtCore.QRect(720, 275, 21, 21))
        self.label_kt2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_kt2.setObjectName("label_kt2")
        self.kt2 = QtWidgets.QSpinBox(self.centralwidget)
        self.kt2.setGeometry(QtCore.QRect(750, 275, 41, 22))
        self.kt2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.kt2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kt2.setMaximum(10000)
        self.kt2.setMinimum(5)
        self.kt2.setObjectName("kt2")
        self.kt2.setProperty("value", 10)

        self.start_y = QtWidgets.QSpinBox(self.centralwidget)
        self.start_y.setGeometry(QtCore.QRect(670, 120, 41, 22))
        self.start_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.start_y.setMaximum(500)
        self.start_y.setProperty("value", 5)
        self.start_y.setObjectName("start_y")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(630, 120, 35, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(708, 120, 35, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.end_y = QtWidgets.QSpinBox(self.centralwidget)
        self.end_y.setGeometry(QtCore.QRect(750, 120, 41, 22))
        self.end_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.end_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.end_y.setMaximum(500)
        self.end_y.setProperty("value", 80)
        self.end_y.setObjectName("end_y")
        self.s1 = QtWidgets.QCheckBox(self.centralwidget)
        self.s1.setGeometry(QtCore.QRect(650, 320, 81, 21))
        self.s1.setChecked(True)
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QCheckBox(self.centralwidget)
        self.s2.setGeometry(QtCore.QRect(650, 340, 81, 21))
        self.s2.setChecked(True)
        self.s2.setObjectName("s2")
        self.s3 = QtWidgets.QCheckBox(self.centralwidget)
        self.s3.setGeometry(QtCore.QRect(650, 360, 81, 21))
        self.s3.setObjectName("s3")
        self.s4 = QtWidgets.QCheckBox(self.centralwidget)
        self.s4.setGeometry(QtCore.QRect(650, 380, 81, 21))
        self.s4.setObjectName("s4")
        self.neighb_size_label = QtWidgets.QLabel(self.centralwidget)
        self.neighb_size_label.setGeometry(QtCore.QRect(740, 340, 30, 22))
        self.neighb_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.neighb_size_label.setObjectName("neighb_size_label")
        self.neighb_size = QtWidgets.QSpinBox(self.centralwidget)
        self.neighb_size.setGeometry(QtCore.QRect(740, 360, 41, 22))
        self.neighb_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.neighb_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.neighb_size.setMaximum(500)
        self.neighb_size.setMinimum(1)
        self.neighb_size.setProperty("value", 20)
        self.neighb_size.setObjectName("neighb_size")
        self.M2 = QtWidgets.QWidget(self.centralwidget)
        self.M2.setGeometry(QtCore.QRect(320, 90, 301, 291))
        self.M2.setObjectName("M2")
        self.M2_describe = QtWidgets.QLabel(self.centralwidget)
        self.M2_describe.setGeometry(QtCore.QRect(310, 105, 200, 20))
        self.M2_describe.setAlignment(QtCore.Qt.AlignLeft| QtCore.Qt.AlignTrailing)
        self.M2_describe.setObjectName("M2_describe")
        self.M1 = QtWidgets.QWidget(self.centralwidget)
        self.M1.setGeometry(QtCore.QRect(10, 90, 301, 291))
        self.M1.setObjectName("M1")
        self.M1_describe = QtWidgets.QLabel(self.centralwidget)
        self.M1_describe.setGeometry(QtCore.QRect(0, 105, 200, 20))
        self.M1_describe.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTrailing)
        self.M1_describe.setObjectName("M1_describe")
        self.M3 = QtWidgets.QWidget(self.centralwidget)
        self.M3.setGeometry(QtCore.QRect(10, 90, 600, 291))
        self.M3.setObjectName("M3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.mapy = QtWidgets.QAction("Mapy", MainWindow)
        self.mapy.setObjectName("mapy")
        self.rozwiazania = QtWidgets.QAction("Rozwiązania", MainWindow)
        self.rozwiazania.setObjectName("rozwiazania")
        self.funkcja_celu = QtWidgets.QAction("Funkcja Celu", MainWindow)
        self.funkcja_celu.setObjectName("funkcja_celu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.mapy)
        self.menubar.addAction(self.rozwiazania)
        self.menubar.addAction(self.funkcja_celu)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Wybór sąsiedztwa"))
        self.wczytaj_mapy.setText(_translate("MainWindow", "Wczytaj mapy"))
        self.test1.setText(_translate("MainWindow", "Test 1"))
        self.test2.setText(_translate("MainWindow", "Test 2"))
        self.test3.setText(_translate("MainWindow", "Test 3"))
        self.H_select.setText(_translate("MainWindow", "H"))
        self.T_select.setText(_translate("MainWindow", "T"))
        self.N_select.setText(_translate("MainWindow", "N"))
        self.wygeneruj_mapy.setText(_translate("MainWindow", "Wygeneruj mapy"))
        self.zapisz_mapy.setText(_translate("MainWindow", "Zapisz mapy"))
        self.label_2.setText(_translate("MainWindow", "Start X"))
        self.label_3.setText(_translate("MainWindow", "End X"))
        self.label_4.setText(_translate("MainWindow", "Rozmiar mapy"))
        self.label_5.setText(_translate("MainWindow", "Pojemność energii"))
        self.label_6.setText(_translate("MainWindow", "Liczba iteracji"))
        self.war_zakonczenia_lab.setText(_translate("MainWindow", "War. zakończenia"))
        self.M1_describe.setText(_translate("MainWindow", ""))
        self.M2_describe.setText(_translate("MainWindow", ""))
        self.uruchom_algorytm.setText(_translate("MainWindow", "Uruchom algorytm"))
        self.label_7.setText(_translate("MainWindow", "HCE"))
        self.label_8.setText(_translate("MainWindow", "TCE"))
        self.label_9.setText(_translate("MainWindow", "TCT"))
        self.label_10.setText(_translate("MainWindow", "HCT"))
        self.label_11.setText(_translate("MainWindow", "Start Y"))
        self.label_12.setText(_translate("MainWindow", "End Y"))
        self.label_aspiration.setText(_translate("MainWindow", "KA+"))
        self.label_random.setText(_translate("MainWindow", "RnP"))
        self.label_kt1.setText(_translate("MainWindow", "kT1"))
        self.label_kt2.setText(_translate("MainWindow", "kT2"))
        self.label_sun_1.setText(_translate("MainWindow", "SN1"))
        self.label_sun_2.setText(_translate("MainWindow", "SN2"))
        self.neighb_size_label.setText(_translate("MainWindow", "Size"))
        self.s1.setText(_translate("MainWindow", "Sąsiedztwo 1"))
        self.s2.setText(_translate("MainWindow", "Sąsiedztwo 2"))
        self.s3.setText(_translate("MainWindow", "Sąsiedztwo 3"))
        self.s4.setText(_translate("MainWindow", "Sąsiedztwo 4"))

